### Get board game details by ID
GET http://localhost:3000/api/plays/167355?fromdate=2025-01-10&todate=2025-04-11
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/plays/167355/summary?fromdate=2025-04-01&todate=2025-04-09
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/plays/167355/summary?fromdate=2025-01-10&todate=2025-04-11
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/plays/167355/winrate?fromdate=2025-04-01&todate=2025-04-11
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/plays/167355/daily?fromdate=2025-04-10&todate=2025-04-11
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/boardgames/167355/
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/boardgames/167355/soloRef
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/boardgames/167355/publishers
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/boardgames/167355/marketplace?fromdate=2025-03-20&sort=ascending
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/search?query=Nemesis&exact=1
x-api-key: debug-api-key
Accept: application/json

### 
GET http://localhost:3000/api/collection/Pregross
x-api-key: debug-api-key
Accept: application/json

###
get https://boardgamegeek.com/xmlapi2/thing?id=999999